
document.documentElement.classList.remove("noscript");
exports.IS_FOOSTACK_DEV=!0;

// to test without worker
//window.Worker = false ;


const keep_fn = require('./domkeep').keep.functions;
for (const el of [document.body, document.head, document.documentElement, document, window, navigator]) {
  const _keep_fn = el instanceof Window ? keep_fn['window'] : el instanceof Document ? keep_fn['document'] : [];
  for (const key in el) {
    if ((typeof el[key] == 'function') && !_keep_fn.includes(key) && !key.includes('addEventListener')) {
      try {
        el[key] = 'undefinednotinkeepfn';
      } catch (e) {}
    }
  }
}

for (const _key of Object.keys(window.console)) {
  if (typeof window.console[_key] === 'function') {
    window.console[_key] = (...args) => { return 'undefinednotinkeepfn'; }
  }
}


const __domething = require('./domething');
const __body_ui = require('./body/ui');
const __body_navigo = require('./body/navigo');


exports.worker_socketio = false ;
exports.postMessage_socketio = (postMessage_data_socketio) => {
  // add pathname to request
  postMessage_data_socketio = Object.assign(postMessage_data_socketio, { path: window.location.pathname });
  if (this.worker_socketio) {
    // worker give object event containing { data: postMessage_data_socketio, .. }
    this.worker_socketio.postMessage(postMessage_data_socketio);
  } else { // use callback
    // giving object containing data like the event
    postMessage_data_socketio = { data: postMessage_data_socketio };
    require('./body/ws')._onmessage(postMessage_data_socketio, (onmessage_cb_data) => {
        onmessage_common_socketio(onmessage_cb_data);
    });
  }
}

// https://www.jstips.co/en/javascript/detect-document-ready-in-pure-js/
const stateCheck_complete = window.setInterval(() => {
  if (document.readyState != 'loading') {
    window.clearInterval(stateCheck_complete);

    this.init_events_restriction()

    // document ready
    //_add_contextmenu_listener();

    __domething.cleanup_prototypes();
    //print_edit_node(document, 'document');
    const stateCheck_cleanup_prototypes = window.setInterval(() => {
      if (__domething.get_state().done.cleanup_prototypes) {
        window.clearInterval(stateCheck_cleanup_prototypes);
        
        __body_ui.init();
        const stateCheck_body_ui_init = window.setInterval(() => {
          if ((typeof __body_ui.get_state().done == 'boolean') && __body_ui.get_state().done) {
            window.clearInterval(stateCheck_body_ui_init);
            
            __body_navigo.init();
            const stateCheck_navigo_init = window.setInterval(() => {
              if (__body_navigo.get_state().done) {
                window.clearInterval(stateCheck_navigo_init);
                
                // SOCKETIO BASE
                if (window.Worker) {
                  const blob_socketio = new Blob( // generated by scripts/make.ws.workerblobs.js
                    [`//${Date.now()}\n`, require('../_generated/ws.blobparts.bundle.js').blobparts],
                    { type: 'text/javascript' }
                  );
                  this.worker_socketio = new Worker(URL.createObjectURL(blob_socketio));
                  this.worker_socketio.addEventListener('message', (e) => {
                    event.preventDefault(); event.stopPropagation();
                    if (!event.isTrusted) { return false }
                    onmessage_common_socketio(e.data); //
                  }, useCapture = false);
                  this.worker_socketio.addEventListener('messageerror', (e) => {
                    event.preventDefault(); event.stopPropagation();
                    if (!event.isTrusted) { return false }
                    __body_ui.page_main_add('_console', 'onmessageerror_socketio', e, details_as_text_node = false, background_color = 'orange');
                  }, useCapture = false);
                  this.worker_socketio.addEventListener('error', (e) => {
                    event.preventDefault(); event.stopPropagation();
                    if (!event.isTrusted) { return false }
                    __body_ui.page_main_add('_console', 'onerror_socketio (worker)', e, details_as_text_node = false, background_color = 'red');
                  }, useCapture = false);
                } else {
                  __body_ui.notification_add("Browser doesn't support Workers ! UI is freezing", 'icon-danger');
                }
                
                // lets init socketio client
                //this.postMessage_socketio({ origin: 'init' });
                this.postMessage_socketio({ origin: 'init' });
            
                
                
                
                
                //console.log(window);
                //console.log(document);
                // TEST BEFORE LOCK
                //this.print_edit_node(document, 'document');
                //this.print_edit_node(window, 'window');
                //this.print_edit_node(navigator, 'navigator');
                //this.print_edit_node(navigator.clipboard, 'navigator.clipboard');
                //this.print_edit_node(document.querySelector('head > style'), 'head > style');
                
                
                
                //TODO review
                //this.check_html_resources();
                
                
                
                // KEEP IT AT THE BOTTOM
                // stopPropagation for _eventsType_keep
                const _events_stop_propagation_without_capture = ['click', 'focus', 'focusout'];
                for (const instance in this._eventsType_keep) {
                  const _nodeinstance = instance == 'window' ? window : document;
                  for (const eventType of this._eventsType_keep[instance]) {
                    if (typeof _nodeinstance.addEventListener == 'function') {
                      _nodeinstance.addEventListener(eventType, (event) => {
                        event.stopPropagation();
                        if (!event.isTrusted) { return false }
                      }, useCapture = !_events_stop_propagation_without_capture.includes(eventType) );
                    }
                  }
                }
                
                __domething.cleanup_elements();
                const stateCheck_cleanup_elements = window.setInterval(() => {
                  if (__domething.get_state().done.cleanup_elements) {
                    window.clearInterval(stateCheck_cleanup_elements);
                    __domething.lock_prototypes();
                    const stateCheck_lock_prototypes = window.setInterval(() => {
                      if (__domething.get_state().done.lock_prototypes) {
                        window.clearInterval(stateCheck_lock_prototypes);

                        
                        // TEST AFTER LOCK
                        this.print_edit_node(document, 'document');
                        this.print_edit_node(Document.prototype, 'Document.prototype');
                        //this.print_edit_node(Navigator.prototype, 'Navigator.prototype');
                        //this.print_edit_node(navigator, 'navigator');
                        //this.print_edit_node(document.querySelector('body > button'), 'body > button');
                        //this.print_edit_node(document.querySelector('body > header > main > nav > section.right'), 'body > header > main > nav > section.right');
                        
                      }
                    }, 0); // stateCheck_lock_prototypes
                  }
                }, 0); // stateCheck_cleanup_elements
                // KEEP IT AT THE BOTTOM
              }
            }, 0); // stateCheck_navigo_init
          }
        }, 20); // stateCheck_body_ui_init
      }
    }, 0); // stateCheck_cleanup_prototypes
  }
}, 0); // stateCheck_complete (readyState)


exports.check_html_resources = () => {
  let _count = 0;
  const _resources_details_array = [];
  const _resources = {
    links: document.querySelectorAll('link'),
    styles: document.querySelectorAll('style'),
    scripts: document.querySelectorAll('script')
  }
  for (const resourcesType in _resources) {
    for (const resource of _resources[resourcesType]) {
      let _resource_details = `${resource.tagName.toLowerCase()};id=${(resource.id && (resource.id.length > 0)) ? resource.id : ''}`;
      _resource_details += (resourcesType == 'scripts')
        ? (resource.src && (resource.src.length > 0))
          ? `;src=/${resource.src.split('/')[resource.src.split('/').length-1]}:[/]${resource.src.split('/').length-1}`
          : ';no-src'
        : (resource.href && (resource.href.length > 0))
          ? `;href=/${resource.href.split('/')[resource.href.split('/').length-1]}:[/]${resource.href.split('/').length-1}`
          : ';no-href' ;
      ;
      const _is_js = (resource.tagName.toLowerCase() === 'script') && resource.id && (resource.id === 'js') && ( this.IS_FOOSTACK_DEV
        ? (resource.src && (resource.src.split('/')[3] == 'main.js'))
        : !resource.src ) ;
      const _is_css = (this.IS_FOOSTACK_DEV ? resource.tagName.toLowerCase() === 'link' : resource.tagName.toLowerCase() === 'style') && resource.id && (resource.id === 'css') && ( this.IS_FOOSTACK_DEV
        ? (resource.href && (resource.href.split('/')[3] == 'main.css'))
        : !resource.href ) ;
      if (!_is_js && !_is_css) {
        __body_ui.notification_add(`Unexpected loaded resource: ${_resource_details}`, 'icon-danger', background_color = 'red');
        __body_ui.page_main_add('_console', `Unexpected loaded resource: ${_resource_details}`, resource.innerHTML, details_as_text_node = true, background_color = 'red');
        resource.remove();
        //return;
      }
      _count++;
      _resources_details_array.push(_resource_details);
    }
  }
  if (_count != 2) {
    __body_ui.notification_add(`Unexpected resource count: ${_count}, expected 2`, 'icon-danger', background_color = 'red');
    __body_ui.page_main_add('_console', `Unexpected resource count: ${_count}, expected 2`, _resources_details_array, details_as_text_node = true, background_color = 'red');
  } else {
    __body_ui.page_main_add('_console', `All resources seems here: ${_count}, expected 2`, _resources_details_array, details_as_text_node = true, background_color = 'green');
  }
}

const onmessage_common_socketio = (data) => {
  __body_ui.page_main_add('_console' , 'onmessage_common_socketio', data);

  const _disconnect = (data) => {
    __body_ui.page_main_add('_connection' , '=========== DISCONNECTED', data, details_as_text_node = false, background_color = 'purple');
    document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-green", "icon-color-red");
    document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-blue", "icon-color-red");
    document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-yellow", "icon-color-red");
    __body_ui.data_from_socket.unset_userid();
  }
  
  if ((typeof data == 'object') && Object.keys(data).includes('on')) {
    //__body_ui.page_main_add(Object.keys(data).includes('deserialized_data')
    //  ? Object.keys(data.deserialized_data).includes('path')
    //    ? data.deserialized_data.path.replace('/','_')
    //    : '_console'
    //  : '_console' , 'onmessage_common_socketio', data) ;
    
    switch (data.on) {
      case "set":
        switch (data.name) {
          case "pub":
            if (Object.keys(data).includes('id')) {
              __body_ui.page_main_add('_connection', '====== USER ID:', data.id);
            } else if (!Object.keys(data).includes('err')) {
              __body_ui.page_main_add('_connection', '=========== SIGN:', 'sign the next message content (paste it in the input below and send it)', details_as_text_node = false, background_color = 'blue');
              __body_ui.page_main_add('_connection', '=========== MESSAGE:', data.message, details_as_text_node = true);
            } else {
              __body_ui.page_main_add('_connection', '=========== OPENPGP PUBLIC KEY NOT VALID:', 'paste your openpgp public key (armored) in the input below and send it', details_as_text_node = false, background_color = 'red');
            }
            break;
        }
        break;
      case "connect":
        document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-red", "icon-color-yellow");
        break;
      case "data ack (hns)":
        document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-yellow", "icon-color-blue");
        __body_ui.page_main_add('_connection', '=========== LOGIN:', 'type: /login_auto or\n      /login to use your keys');
        break;
      case "data":
        if (data.deserialized_data) {
          if (typeof data.deserialized_data.response == 'object') {
            if ((data.deserialized_data.data == '/login') && Object.keys(data.deserialized_data.response).includes('seed')) { // SEED
              __body_ui.page_main_add('_connection', '=========== OPENPGP PUBLIC KEY:', 'paste your openpgp public key (armored) in the input below and send it', details_as_text_node = false, background_color = 'blue');
            } else if (Object.keys(data.deserialized_data.response).includes('is_connected') && data.deserialized_data.response.is_connected) { // CONNECTED
              __body_ui.page_main_add('_connection' , '=========== CONNECTED', data, details_as_text_node = false, background_color = 'green');
              document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-blue", "icon-color-green");
              __body_ui.data_from_socket.set_userid(data.deserialized_data.id);
            } else if (Object.keys(data.deserialized_data.response).includes('is_disconnected') && data.deserialized_data.response.is_disconnected) { // DISCONNECTED
              _disconnect(data);
            }
          }
        }
        break;
      case "disconnect":
        _disconnect(data);
        break;
    }
  }
}

exports.print_edit_node = (_node, _node_name = '_node', _keep = []) => {
    //const _node = document.querySelector('body'); // Document.prototype or something else
    //const _keep = [ // keep getAttribute
    //  "test"
    //]; 
    const isundefinedprototype = [];
    const isundefinednotinkeepfn = [];
    const isnullundefined = [];
    const isnotnull = [];
    for (const key in _node) {
      if (!_keep.includes(key)) {
        try {
          //_node[key] = null;
        } catch (e) {}
      }
      try {
        if (_node[key] == 'undefinedprototype') {
          isundefinedprototype.push(key);
        } else if (_node[key] == 'undefinednotinkeepfn') {
          isundefinednotinkeepfn.push(key);
        } else if ((_node[key] == null) || (_node[key] == undefined)) {
          isnullundefined.push(key);
        } else {
          isnotnull.push(key);
        }
      } catch (e) {}
    }
    __body_ui.page_main_add('_console', `${_node_name} undefinedprototype`, isundefinedprototype);
    __body_ui.page_main_add('_console', `${_node_name} undefinednotinkeepfn`, isundefinednotinkeepfn);
    __body_ui.page_main_add('_console', `${_node_name} null || undefined`, isnullundefined);
    __body_ui.page_main_add('_console', `${_node_name}   => else`, isnotnull);
}


exports.init_events_restriction = () => {

  const _handle_event_restriction = (node) => {
    for (const key in node) {
      if(/^on/.test(key)) {
          const eventType = key.substr(2);

          //const _nodename = node instanceof Window ? 'window' : 'document';
          
          
          if (!require('./domkeep').keep.events.includes(eventType)) {
            try {
              node.addEventListener(eventType, (event) => {
                if (event.preventDefault) { event.preventDefault(); }
                if (event.stopPropagation) { event.stopPropagation(); }
                if (eventType.includes('error')) {
                  const _el_triggered = `${event.target && event.target.tagName ? event.target.tagName.toLowerCase() : ''}:${event.target.class ? event.target.class : ''}`;
                  const _el_listen = `${event.currentTarget && event.currentTarget.tagName ? event.currentTarget.tagName.toLowerCase() : ''}:${event.currentTarget.class ? event.currentTarget.class : ''}`;
                  const _message = `triggered=${_el_triggered}; listener=${_el_listen}; eventType=${eventType}; filename=${event.filename}; message=${event.message}; errorString=${JSON.stringify(event.error)}`;
                  const _messagetextnode = document.createTextNode(_message);
                  (typeof window.console == 'object') && Object.keys(window.console).includes('_is_custom') && window.console._is_custom
                    ? window.console.debug(_message, `ERROR: ${_el_triggered}`, background_color = 'red')
                    : this.IS_FOOSTACK_DEV
                      ? document.querySelector('body > main > main > main > ._console').appendChild(_messagetextnode)
                      : false ;
                }
                
                // const _messagetextnode = document.createTextNode(_message);
                // if (!eventType.includes('error') && !eventType.includes('pointer') && !eventType.includes('wheel') && !eventType.includes('mouse') && !eventType.includes('device') && !eventType.includes('scroll')) {
                //   document.querySelector('body > main > main > main > ._console').innerHTML += `- headerbody:debug:${eventType}`;
                // }
              }, useCapture = true);
              
            } catch (e) {
              if ((typeof window.console == 'object') && Object.keys(window.console).includes('log') && (typeof window.console.log === 'function')) {
                console.log("error in a try catch, you can ignore.");
              }
            }
          }
      }
    }
  }
  try {
    // loop on childNodes
    const _loop = (node) => {
        _handle_event_restriction(node);
        
        if (node.shadowRoot) {
          _loop(node.shadowRoot);
        }
        const nodes = node.childNodes;
        if(nodes && nodes.length > 0){
          for (let i = 0; i < nodes.length; i++){
            _loop(nodes[i]);
            if (node instanceof Document && (i == nodes.length-1)) {
              // if Window.prototype.dispatchEvent is nulled (maybe)
              //Navigo doc: If there is a `popstate` event dispatched (this happens when the user manually changes the browser location by hitting for example the back button)
              window.addEventListener('popstate', (event) => {
                  event.preventDefault(); event.stopPropagation();
                  if (!event.isTrusted) { return false }
                  try {
                    window.router_resolve();
                  } catch (e) {}
              }, useCapture = true);
              
              for (const el of [window, document, document.documentElement, document.head, document.body]) {
                el.addEventListener = 'undefinednotinkeepfn'
              }
              _state.done = true ; // last child is body script
            }
          }
        }
    }
    //
    _loop(window);
    _loop(document);
  } catch (e) {}
}


/*
const _add_contextmenu_listener = () => {
  window.addEventListener('contextmenu', (event) => {
    event.preventDefault(); event.stopPropagation();
    if (!event.isTrusted) { return false }
    if (event.target.tagName.toUpperCase() != 'TEXTAREA' && event.target.tagName.toUpperCase() != 'INPUT') {
      const selection = window.getSelection();
      const range = document.createRange();
      range.selectNodeContents(event.target);
      selection.removeAllRanges();
      selection.addRange(range);
      if (window.getSelection().toString().length > 0) {
        // https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
        console.log(navigator.clipboard.writeText);
        navigator.clipboard.writeText(window.getSelection().toString());
      }
    } else {
      event.target.value = '';
      //event.target.value = await navigator.clipboard.readText();
    }
  }, useCapture = false);
}
*/


/*
window.addEventListener('contextmenu', (event) => {
  event.preventDefault(); event.stopPropagation();
  if (!event.isTrusted) { return false }
  if (event.target.tagName.toUpperCase() != 'TEXTAREA' && event.target.tagName.toUpperCase() != 'INPUT') {
    const selection = window.getSelection();
    const range = document.createRange();
    range.selectNodeContents(event.target);
    selection.removeAllRanges();
    selection.addRange(range);
    if (window.getSelection().toString().length > 0) {
      // https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
      console.log(navigator.clipboard.writeText);
      navigator.clipboard.writeText(window.getSelection().toString());
    }
  } else {
    event.target.value = '';
    //event.target.value = await navigator.clipboard.readText();
  }
}, useCapture = false);

exports._copy_selection_to_clipboard = () => {
  if (navigator && Object.keys(navigator).includes('clipboard') && Object.keys(navigator.clipboard).includes('writeText')) {
    if (window.getSelection().toString() > 0) {
      navigator.clipboard.writeText(window.getSelection().toString());
    }
  }
}
const _handle_selection = (event) => {
  const selection = window.getSelection();
  const range = document.createRange();
  range.selectNodeContents(event.target);
  selection.removeAllRanges();
  selection.addRange(range);
  __body_ui.global_ui_vars.copy.content = window.getSelection().toString();
}
const _handle_copy_button = (event) => {
  if (window.getSelection().toString().length > 0) {
    if (__body_ui.global_ui_vars.copy.button) {
      __body_ui.global_ui_vars.copy.button.remove();
      __body_ui.global_ui_vars.copy.button = false ;
    }
    const _button = document.querySelector('body > button').cloneNode(deep = false);
    //_button.innerHTML = 'COPY';
    _button.classList.add('copy');
    _button.addEventListener('click', (event_button) => {
      event_button.preventDefault(); event_button.stopPropagation();
      navigator.clipboard.writeText(window.getSelection().toString());
      //this._copy_selection_to_clipboard();
      __body_ui.global_ui_vars.copy.button.remove();
      __body_ui.global_ui_vars.copy.button = false ;
    }, useCapture = false);
    __body_ui.global_ui_vars.copy.button = _button;
    event.target.parentNode.appendChild(_button);
  }
}
window.addEventListener('selectstart', (event) => {
  event.preventDefault(); event.stopPropagation();
  //if (!event.isTrusted) { return false }
  _handle_selection(event);
  _handle_copy_button(event);
  console.log(window.getSelection().toString());
}, useCapture = false);
document.addEventListener('copy', (event) => {
  event.preventDefault(); event.stopPropagation();
  //if (!event.isTrusted) { return false }
  event.clipboardData.setData('text/plain', window.getSelection().toString());
}, useCapture = false);
*/
